// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPVmiDOSHx3vPmLqz1rQjkiZi5L0dtc2Q',
    appId: '1:246632150770:web:92d1a726480ed2ed16426b',
    messagingSenderId: '246632150770',
    projectId: 'final-gas-iot',
    authDomain: 'final-gas-iot.firebaseapp.com',
    storageBucket: 'final-gas-iot.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQsV4u4TK94WdIJ34D6Jw0CGfcn3n5ELE',
    appId: '1:246632150770:android:d0eb1f20ae0d371716426b',
    messagingSenderId: '246632150770',
    projectId: 'final-gas-iot',
    storageBucket: 'final-gas-iot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7c1NHMNTnGdNaAd94KmeB97f_TrZNcfc',
    appId: '1:246632150770:ios:98c919718993883916426b',
    messagingSenderId: '246632150770',
    projectId: 'final-gas-iot',
    storageBucket: 'final-gas-iot.appspot.com',
    iosBundleId: 'com.example.kiplihJum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7c1NHMNTnGdNaAd94KmeB97f_TrZNcfc',
    appId: '1:246632150770:ios:eb0186bbe5347bf716426b',
    messagingSenderId: '246632150770',
    projectId: 'final-gas-iot',
    storageBucket: 'final-gas-iot.appspot.com',
    iosBundleId: 'com.example.kiplihJum.RunnerTests',
  );
}
