// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKTSTbx4lm2z80Ss74QMsLtT_OGKp_Srg',
    appId: '1:942000905666:web:2d2154eee7ffba16430a5b',
    messagingSenderId: '942000905666',
    projectId: 'iot-home-8735c',
    authDomain: 'iot-home-8735c.firebaseapp.com',
    databaseURL: 'https://iot-home-8735c-default-rtdb.firebaseio.com',
    storageBucket: 'iot-home-8735c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXciZkw7d-KZ-3HUAES_OxRcgxcOSZQ2E',
    appId: '1:942000905666:android:157cd38c42e0733f430a5b',
    messagingSenderId: '942000905666',
    projectId: 'iot-home-8735c',
    databaseURL: 'https://iot-home-8735c-default-rtdb.firebaseio.com',
    storageBucket: 'iot-home-8735c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1VZ9TOhxwnZBfEEjoP63qc9YZj8ada8E',
    appId: '1:942000905666:ios:037895586529381a430a5b',
    messagingSenderId: '942000905666',
    projectId: 'iot-home-8735c',
    databaseURL: 'https://iot-home-8735c-default-rtdb.firebaseio.com',
    storageBucket: 'iot-home-8735c.appspot.com',
    iosBundleId: 'com.example.kiplihJum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1VZ9TOhxwnZBfEEjoP63qc9YZj8ada8E',
    appId: '1:942000905666:ios:b9dc80e9c6e9ff9e430a5b',
    messagingSenderId: '942000905666',
    projectId: 'iot-home-8735c',
    databaseURL: 'https://iot-home-8735c-default-rtdb.firebaseio.com',
    storageBucket: 'iot-home-8735c.appspot.com',
    iosBundleId: 'com.example.kiplihJum.RunnerTests',
  );
}
